- hosts: all
  become: yes
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Clone YOLO repository
      git:
        repo: 'https://github.com/LeslieKogi/yolo.git'
        dest: /home/vagrant/yolo
        version: master 

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
      tags: setup

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: docker  

    - name: Install pyton3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      tags: docker

    - name: Install Docker SDK for Python
      pip:
        name: docker
      tags: docker

    - name: Create Docker network
      community.docker.docker_network:
       name: app-net
       driver: bridge
       ipam_config:
        - subnet: 172.20.0.0/16
          iprange: 172.20.0.0/16
       attachable: yes
      tags: docker

    