- hosts: all
  become: yes
  tasks:
    - name: Clone YOLO repository
      git:
        repo: 'https://github.com/LeslieKogi/yolo.git'
        dest: /home/vagrant/yolo
        version: master 

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
      tags: setup

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: docker  