---
# tasks file for backend
- name: Pull backend image from Docker Hub
  community.docker.docker_image:
    name: "{{ backend_image_name }}"
    tag: "{{ backend_image_tag }}"
    source: pull
  tags: backend

- name: Run backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image_name }}:{{ backend_image_tag }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ backend_network }}"
    env: "{{ backend_env }}"
    published_ports:
          - "{{ backend_port }}"
  tags: backend