---
# tasks file for frontend
- name: Pull frontend image from Docker Hub
  community.docker.docker_image:
    name: thandie/yolo-frontend
    tag: "1.0.3"
    source: pull
  tags: frontend

- name: Run frontend container
  community.docker.docker_container:
   name: yolo-frontend
   image: thandie/yolo-frontend:1.0.3
   state: started
   restart_policy: always
   networks:
    - name: app-net
   published_ports:
    - "3000:80"
  tags: frontend