---
# tasks file for docker
- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: docker  

- name: Install pyton3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  tags: docker

- name: Install Docker SDK for Python
  pip:
    name: docker
  tags: docker

- name: Create Docker network
  community.docker.docker_network:
    name: app-net
    driver: bridge
    ipam_config:
      - subnet: 172.20.0.0/16
        iprange: 172.20.0.0/16
    attachable: yes
  tags: docker

- name: Create Volume
  community.docker.docker_volume:
    name: app-mongo-data
    driver: local
  tags: docker 